- name: setup cart
  hosts: cart
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: add application user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop application user
      shell: /sbin/nologin
      system: true
      home: /app

# safe to remove and create again
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create application directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: remove cart file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: download cart code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app

  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

      
  - name: start cart service
    ansible.builtin.systemd_service:
      name: cart
      state: restarted
      enabled: yes
      daemon_reload: true