- name: ec2 
  hosts: local
  connection: local
  vars:
    ami: ami-09c813fb71547fc4f
    sg_id: sg-017681bac367675c7
    zone_id: "Z0379910K30ZWY5SALMW"
    domain_name: "gopi29.fun"
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output


- name: create route53 record
  amazon.aws.route53:
    state: present
    zone: "{{ domain_name  }}"
    record: "{{ item.item }}.{{ domain_name }}" #mongodb.gopi29.fun
    type: A
    ttl: 1
    value: "{{ item.instances[0].private_ip_address }}"
    overwrite: true
  loop: "{{ ec2_output.results }}"