- name: function
  hosts: local
  connection: local
  vars:
    technology: ansible, devops, aws, linux
    #map == dict
  tags:
    Appilcation: Ansible
    Environment: Devops
  tasks:
  - name: print the items
    ansible.builtin.debug:
      msg: "the name is {{ name | default('gopi') }}"

  - name: print string to list
    ansible.builtin.debug:
      msg: "{{ technology | split(',') }}"

  - name: map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}" 