- name: loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print the items
    ansible.builtin.package:
      name: "item is {{ item.name }}"
      state: "state is {{ item.state }}"
    loop:
    - { name: "nginx", state: "absent"}