- name: payment server
  hosts: payment
  become: yes
  tasks:
  - name: install python3.9
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3.9
    - gcc
    - python3.9-devel

  - name: add application user
    ansible.builtin.user:
      name: roboshop
      comment: roboshop application user
      shell: /sbin/nologin
      system: true
      home: /app

# safe to remove and create again
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create application directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: remove payment file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: download payment code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip

  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install python dependencies
    ansible.builtin.pip:  
      requirements: /app/requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy payment service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload
    ansible.builtin.systemd:
      daemon_reload: yes
      state: started
      name: payment
      enabled: yes